Map getCountries() {
  Map _map = {"options": {}};

  for (var i = 1; i < json.length; i++) {
    _map["options"][i.toString()] = json[i];
    _map["options"][i.toString()]["id"] = i;
    _map["options"][i.toString()]["next"] = "6";
  }

  // Map _newMap = {};

  // _map["options"].forEach((key, value) {});

  print(_map);
  return _map;
}

List json = [
  {"id": 1, "text": "Afghanistan", "code": "AF"},
  {"id": 1, "text": "Åland Islands", "code": "AX"},
  {"id": 1, "text": "Albania", "code": "AL"},
  {"id": 1, "text": "Algeria", "code": "DZ"},
  {"id": 1, "text": "American Samoa", "code": "AS"},
  {"id": 1, "text": "AndorrA", "code": "AD"},
  {"id": 1, "text": "Angola", "code": "AO"},
  {"id": 1, "text": "Anguilla", "code": "AI"},
  {"id": 1, "text": "Antarctica", "code": "AQ"},
  {"id": 1, "text": "Antigua and Barbuda", "code": "AG"},
  {"id": 1, "text": "Argentina", "code": "AR"},
  {"id": 1, "text": "Armenia", "code": "AM"},
  {"id": 1, "text": "Aruba", "code": "AW"},
  {"id": 1, "text": "Australia", "code": "AU"},
  {"id": 1, "text": "Austria", "code": "AT"},
  {"id": 1, "text": "Azerbaijan", "code": "AZ"},
  {"id": 1, "text": "Bahamas", "code": "BS"},
  {"id": 1, "text": "Bahrain", "code": "BH"},
  {"id": 1, "text": "Bangladesh", "code": "BD"},
  {"id": 1, "text": "Barbados", "code": "BB"},
  {"id": 1, "text": "Belarus", "code": "BY"},
  {"id": 1, "text": "Belgium", "code": "BE"},
  {"id": 1, "text": "Belize", "code": "BZ"},
  {"id": 1, "text": "Benin", "code": "BJ"},
  {"id": 1, "text": "Bermuda", "code": "BM"},
  {"id": 1, "text": "Bhutan", "code": "BT"},
  {"id": 1, "text": "Bolivia", "code": "BO"},
  {"id": 1, "text": "Bosnia and Herzegovina", "code": "BA"},
  {"id": 1, "text": "Botswana", "code": "BW"},
  {"id": 1, "text": "Bouvet Island", "code": "BV"},
  {"id": 1, "text": "Brazil", "code": "BR"},
  {"id": 1, "text": "British Indian Ocean Territory", "code": "IO"},
  {"id": 1, "text": "Brunei Darussalam", "code": "BN"},
  {"id": 1, "text": "Bulgaria", "code": "BG"},
  {"id": 1, "text": "Burkina Faso", "code": "BF"},
  {"id": 1, "text": "Burundi", "code": "BI"},
  {"id": 1, "text": "Cambodia", "code": "KH"},
  {"id": 1, "text": "Cameroon", "code": "CM"},
  {"id": 1, "text": "Canada", "code": "CA"},
  {"id": 1, "text": "Cape Verde", "code": "CV"},
  {"id": 1, "text": "Cayman Islands", "code": "KY"},
  {"id": 1, "text": "Central African Republic", "code": "CF"},
  {"id": 1, "text": "Chad", "code": "TD"},
  {"id": 1, "text": "Chile", "code": "CL"},
  {"id": 1, "text": "China", "code": "CN"},
  {"id": 1, "text": "Christmas Island", "code": "CX"},
  {"id": 1, "text": "Cocos (Keeling) Islands", "code": "CC"},
  {"id": 1, "text": "Colombia", "code": "CO"},
  {"id": 1, "text": "Comoros", "code": "KM"},
  {"id": 1, "text": "Congo", "code": "CG"},
  {"id": 1, "text": "Congo, The Democratic Republic of the", "code": "CD"},
  {"id": 1, "text": "Cook Islands", "code": "CK"},
  {"id": 1, "text": "Costa Rica", "code": "CR"},
  {"id": 1, "text": "Croatia", "code": "HR"},
  {"id": 1, "text": "Cuba", "code": "CU"},
  {"id": 1, "text": "Cyprus", "code": "CY"},
  {"id": 1, "text": "Czech Republic", "code": "CZ"},
  {"id": 1, "text": "Denmark", "code": "DK"},
  {"id": 1, "text": "Djibouti", "code": "DJ"},
  {"id": 1, "text": "Dominica", "code": "DM"},
  {"id": 1, "text": "Dominican Republic", "code": "DO"},
  {"id": 1, "text": "Ecuador", "code": "EC"},
  {"id": 1, "text": "Egypt", "code": "EG"},
  {"id": 1, "text": "El Salvador", "code": "SV"},
  {"id": 1, "text": "Equatorial Guinea", "code": "GQ"},
  {"id": 1, "text": "Eritrea", "code": "ER"},
  {"id": 1, "text": "Estonia", "code": "EE"},
  {"id": 1, "text": "Ethiopia", "code": "ET"},
  {"id": 1, "text": "Falkland Islands (Malvinas)", "code": "FK"},
  {"id": 1, "text": "Faroe Islands", "code": "FO"},
  {"id": 1, "text": "Fiji", "code": "FJ"},
  {"id": 1, "text": "Finland", "code": "FI"},
  {"id": 1, "text": "France", "code": "FR"},
  {"id": 1, "text": "French Guiana", "code": "GF"},
  {"id": 1, "text": "French Polynesia", "code": "PF"},
  {"id": 1, "text": "French Southern Territories", "code": "TF"},
  {"id": 1, "text": "Gabon", "code": "GA"},
  {"id": 1, "text": "Gambia", "code": "GM"},
  {"id": 1, "text": "Georgia", "code": "GE"},
  {"id": 1, "text": "Germany", "code": "DE"},
  {"id": 1, "text": "Ghana", "code": "GH"},
  {"id": 1, "text": "Gibraltar", "code": "GI"},
  {"id": 1, "text": "Greece", "code": "GR"},
  {"id": 1, "text": "Greenland", "code": "GL"},
  {"id": 1, "text": "Grenada", "code": "GD"},
  {"id": 1, "text": "Guadeloupe", "code": "GP"},
  {"id": 1, "text": "Guam", "code": "GU"},
  {"id": 1, "text": "Guatemala", "code": "GT"},
  {"id": 1, "text": "Guernsey", "code": "GG"},
  {"id": 1, "text": "Guinea", "code": "GN"},
  {"id": 1, "text": "Guinea-Bissau", "code": "GW"},
  {"id": 1, "text": "Guyana", "code": "GY"},
  {"id": 1, "text": "Haiti", "code": "HT"},
  {"id": 1, "text": "Heard Island and Mcdonald Islands", "code": "HM"},
  {"id": 1, "text": "Holy See (Vatican City State)", "code": "VA"},
  {"id": 1, "text": "Honduras", "code": "HN"},
  {"id": 1, "text": "Hong Kong", "code": "HK"},
  {"id": 1, "text": "Hungary", "code": "HU"},
  {"id": 1, "text": "Iceland", "code": "IS"},
  {"id": 1, "text": "India", "code": "IN"},
  {"id": 1, "text": "Indonesia", "code": "ID"},
  {"id": 1, "text": "Iran, Islamic Republic Of", "code": "IR"},
  {"id": 1, "text": "Iraq", "code": "IQ"},
  {"id": 1, "text": "Ireland", "code": "IE"},
  {"id": 1, "text": "Isle of Man", "code": "IM"},
  {"id": 1, "text": "Israel", "code": "IL"},
  {"id": 1, "text": "Italy", "code": "IT"},
  {"id": 1, "text": "Jamaica", "code": "JM"},
  {"id": 1, "text": "Japan", "code": "JP"},
  {"id": 1, "text": "Jersey", "code": "JE"},
  {"id": 1, "text": "Jordan", "code": "JO"},
  {"id": 1, "text": "Kazakhstan", "code": "KZ"},
  {"id": 1, "text": "Kenya", "code": "KE"},
  {"id": 1, "text": "Kiribati", "code": "KI"},
  {"id": 1, "text": "Korea, Democratic PeopleS Republic of", "code": "KP"},
  {"id": 1, "text": "Korea, Republic of", "code": "KR"},
  {"id": 1, "text": "Kuwait", "code": "KW"},
  {"id": 1, "text": "Kyrgyzstan", "code": "KG"},
  {"id": 1, "text": "Lao PeopleS Democratic Republic", "code": "LA"},
  {"id": 1, "text": "Latvia", "code": "LV"},
  {"id": 1, "text": "Lebanon", "code": "LB"},
  {"id": 1, "text": "Lesotho", "code": "LS"},
  {"id": 1, "text": "Liberia", "code": "LR"},
  {"id": 1, "text": "Libyan Arab Jamahiriya", "code": "LY"},
  {"id": 1, "text": "Liechtenstein", "code": "LI"},
  {"id": 1, "text": "Lithuania", "code": "LT"},
  {"id": 1, "text": "Luxembourg", "code": "LU"},
  {"id": 1, "text": "Macao", "code": "MO"},
  {"id": 1, "text": "Macedonia, The Former Yugoslav Republic of", "code": "MK"},
  {"id": 1, "text": "Madagascar", "code": "MG"},
  {"id": 1, "text": "Malawi", "code": "MW"},
  {"id": 1, "text": "Malaysia", "code": "MY"},
  {"id": 1, "text": "Maldives", "code": "MV"},
  {"id": 1, "text": "Mali", "code": "ML"},
  {"id": 1, "text": "Malta", "code": "MT"},
  {"id": 1, "text": "Marshall Islands", "code": "MH"},
  {"id": 1, "text": "Martinique", "code": "MQ"},
  {"id": 1, "text": "Mauritania", "code": "MR"},
  {"id": 1, "text": "Mauritius", "code": "MU"},
  {"id": 1, "text": "Mayotte", "code": "YT"},
  {"id": 1, "text": "Mexico", "code": "MX"},
  {"id": 1, "text": "Micronesia, Federated States of", "code": "FM"},
  {"id": 1, "text": "Moldova, Republic of", "code": "MD"},
  {"id": 1, "text": "Monaco", "code": "MC"},
  {"id": 1, "text": "Mongolia", "code": "MN"},
  {"id": 1, "text": "Montserrat", "code": "MS"},
  {"id": 1, "text": "Morocco", "code": "MA"},
  {"id": 1, "text": "Mozambique", "code": "MZ"},
  {"id": 1, "text": "Myanmar", "code": "MM"},
  {"id": 1, "text": "Namibia", "code": "NA"},
  {"id": 1, "text": "Nauru", "code": "NR"},
  {"id": 1, "text": "Nepal", "code": "NP"},
  {"id": 1, "text": "Netherlands", "code": "NL"},
  {"id": 1, "text": "Netherlands Antilles", "code": "AN"},
  {"id": 1, "text": "New Caledonia", "code": "NC"},
  {"id": 1, "text": "New Zealand", "code": "NZ"},
  {"id": 1, "text": "Nicaragua", "code": "NI"},
  {"id": 1, "text": "Niger", "code": "NE"},
  {"id": 1, "text": "Nigeria", "code": "NG"},
  {"id": 1, "text": "Niue", "code": "NU"},
  {"id": 1, "text": "Norfolk Island", "code": "NF"},
  {"id": 1, "text": "Northern Mariana Islands", "code": "MP"},
  {"id": 1, "text": "Norway", "code": "NO"},
  {"id": 1, "text": "Oman", "code": "OM"},
  {"id": 1, "text": "Pakistan", "code": "PK"},
  {"id": 1, "text": "Palau", "code": "PW"},
  {"id": 1, "text": "Palestinian Territory, Occupied", "code": "PS"},
  {"id": 1, "text": "Panama", "code": "PA"},
  {"id": 1, "text": "Papua New Guinea", "code": "PG"},
  {"id": 1, "text": "Paraguay", "code": "PY"},
  {"id": 1, "text": "Peru", "code": "PE"},
  {"id": 1, "text": "Philippines", "code": "PH"},
  {"id": 1, "text": "Pitcairn", "code": "PN"},
  {"id": 1, "text": "Poland", "code": "PL"},
  {"id": 1, "text": "Portugal", "code": "PT"},
  {"id": 1, "text": "Puerto Rico", "code": "PR"},
  {"id": 1, "text": "Qatar", "code": "QA"},
  {"id": 1, "text": "Reunion", "code": "RE"},
  {"id": 1, "text": "Romania", "code": "RO"},
  {"id": 1, "text": "Russian Federation", "code": "RU"},
  {"id": 1, "text": "RWANDA", "code": "RW"},
  {"id": 1, "text": "Saint Helena", "code": "SH"},
  {"id": 1, "text": "Saint Kitts and Nevis", "code": "KN"},
  {"id": 1, "text": "Saint Lucia", "code": "LC"},
  {"id": 1, "text": "Saint Pierre and Miquelon", "code": "PM"},
  {"id": 1, "text": "Saint Vincent and the Grenadines", "code": "VC"},
  {"id": 1, "text": "Samoa", "code": "WS"},
  {"id": 1, "text": "San Marino", "code": "SM"},
  {"id": 1, "text": "Sao Tome and Principe", "code": "ST"},
  {"id": 1, "text": "Saudi Arabia", "code": "SA"},
  {"id": 1, "text": "Senegal", "code": "SN"},
  {"id": 1, "text": "Serbia and Montenegro", "code": "CS"},
  {"id": 1, "text": "Seychelles", "code": "SC"},
  {"id": 1, "text": "Sierra Leone", "code": "SL"},
  {"id": 1, "text": "Singapore", "code": "SG"},
  {"id": 1, "text": "Slovakia", "code": "SK"},
  {"id": 1, "text": "Slovenia", "code": "SI"},
  {"id": 1, "text": "Solomon Islands", "code": "SB"},
  {"id": 1, "text": "Somalia", "code": "SO"},
  {"id": 1, "text": "South Africa", "code": "ZA"},
  {
    "id": 1,
    "text": "South Georgia and the South Sandwich Islands",
    "code": "GS"
  },
  {"id": 1, "text": "Spain", "code": "ES"},
  {"id": 1, "text": "Sri Lanka", "code": "LK"},
  {"id": 1, "text": "Sudan", "code": "SD"},
  {"id": 1, "text": "Suriname", "code": "SR"},
  {"id": 1, "text": "Svalbard and Jan Mayen", "code": "SJ"},
  {"id": 1, "text": "Swaziland", "code": "SZ"},
  {"id": 1, "text": "Sweden", "code": "SE"},
  {"id": 1, "text": "Switzerland", "code": "CH"},
  {"id": 1, "text": "Syrian Arab Republic", "code": "SY"},
  {"id": 1, "text": "Taiwan, Province of China", "code": "TW"},
  {"id": 1, "text": "Tajikistan", "code": "TJ"},
  {"id": 1, "text": "Tanzania, United Republic of", "code": "TZ"},
  {"id": 1, "text": "Thailand", "code": "TH"},
  {"id": 1, "text": "Timor-Leste", "code": "TL"},
  {"id": 1, "text": "Togo", "code": "TG"},
  {"id": 1, "text": "Tokelau", "code": "TK"},
  {"id": 1, "text": "Tonga", "code": "TO"},
  {"id": 1, "text": "Trinidad and Tobago", "code": "TT"},
  {"id": 1, "text": "Tunisia", "code": "TN"},
  {"id": 1, "text": "Turkey", "code": "TR"},
  {"id": 1, "text": "Turkmenistan", "code": "TM"},
  {"id": 1, "text": "Turks and Caicos Islands", "code": "TC"},
  {"id": 1, "text": "Tuvalu", "code": "TV"},
  {"id": 1, "text": "Uganda", "code": "UG"},
  {"id": 1, "text": "Ukraine", "code": "UA"},
  {"id": 1, "text": "United Arab Emirates", "code": "AE"},
  {"id": 1, "text": "United Kingdom", "code": "GB"},
  {"id": 1, "text": "United States", "code": "US"},
  {"id": 1, "text": "United States Minor Outlying Islands", "code": "UM"},
  {"id": 1, "text": "Uruguay", "code": "UY"},
  {"id": 1, "text": "Uzbekistan", "code": "UZ"},
  {"id": 1, "text": "Vanuatu", "code": "VU"},
  {"id": 1, "text": "Venezuela", "code": "VE"},
  {"id": 1, "text": "Viet Nam", "code": "VN"},
  {"id": 1, "text": "Virgin Islands, British", "code": "VG"},
  {"id": 1, "text": "Virgin Islands, U.S.", "code": "VI"},
  {"id": 1, "text": "Wallis and Futuna", "code": "WF"},
  {"id": 1, "text": "Western Sahara", "code": "EH"},
  {"id": 1, "text": "Yemen", "code": "YE"},
  {"id": 1, "text": "Zambia", "code": "ZM"},
  {"id": 1, "text": "Zimbabwe", "code": "ZW"}
];
